version: '3.4'

services:
  cleanarchmvc.webui:
    image: ${DOCKER_REGISTRY-}cleanarchmvcwebui
    build:
      context: .
      dockerfile: CleanArchMvc.WebUI/Dockerfile
  cleanarchmvc.sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver